config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'gross' => 'posts#index'

  get 'posts/index' => 'posts#index'

  get 'posts/new' => 'posts#new'

  post 'posts' => 'posts#create'

  get 'posts/:id' => 'posts#show',as: 'post'
  
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'
  get 'posts/:id/edit' => 'posts#edit', as:'edit_post'

  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 } 
  
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

         
before_action :configure_permitted_parameters, if: :devise_controller?

protected
def configure_permitted_parameters
  
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  
  devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  before_action :authenticate_user!, only: [:new, :create] 
  
    def index
      if params[:search] == nil
        @posts= Post.all
      elsif params[:search] == ''
        @posts= Post.all
      else
        #部分検索
        @posts = Post.where("body LIKE ? ",'%' + params[:search] + '%')
      end
    end
  

    def new
      @post = Post.new
    end

    def create
      post = Post.new(post_params)

      post.user_id = current_user.id

      if post.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end

    

    private
    def post_params
      params.require(:post).permit(:title, :give, :want, :about, :serve, :image)
    end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gross</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if user_signed_in? %>
    <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "新規登録", new_user_registration_path %></li>
    <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
  </head>  

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Gross 交換サイト</h1>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<h3>募集一覧</h3>
<%= link_to "新規募集へ", posts_new_path %>
<div class="posts-container">

  <% @posts.each do |t| %>
    <div class="post">
      <%= t.title %>
      <%= t.give %>
      <%= t.want %>
      <%= t.about %>
      <%= t.serve %>
      <%= t.image %>
      <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>　#追記
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>　
<% end %>

app/views/posts/new.html.erb
<h1>新規募集投稿</h1>
<h3>募集内容を入力してください</h3>
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :size => 140 %>
  </div>

  <div class="field">
    <%= f.label :give %>
    <%= f.text_field :give, :size => 140 %>
  </div>

  <div class="field">
    <%= f.label :want %>
    <%= f.text_field :want, :size => 140 %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :serve %>
    <%= f.select :serve, 
    [["郵送", "郵送"],  
    ["手渡し", "手渡し"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <%= f.submit "募集を開始する" %>
<% end %>
<%= link_to "Tweet一覧に戻る", posts_index_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>



<%= link_to "Tweet一覧に戻る", tweets_path %>